-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 19:35:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema proyecfabricacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecfabricacion` ;

-- -----------------------------------------------------
-- Schema proyecfabricacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecfabricacion` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecfabricacion` ;

-- -----------------------------------------------------
-- Table `proyecfabricacion`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(255) NULL DEFAULT NULL,
  `cantidadPorProducto` INT NULL DEFAULT NULL,
  `precioUnidad` DECIMAL(10,0) NULL DEFAULT NULL,
  `unidadExistencia` INT NULL DEFAULT NULL,
  `unidadPedido` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecfabricacion`.`bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`bodega` (
  `idBodega` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `accion` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `pedidos` VARCHAR(255) NULL DEFAULT NULL,
  `producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idBodega`, `producto_idProducto`),
  CONSTRAINT `fk_bodega_producto1`
    FOREIGN KEY (`producto_idProducto`)
    REFERENCES `proyecfabricacion`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_bodega_producto1_idx` ON `proyecfabricacion`.`bodega` (`producto_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `proyecfabricacion`.`reportecalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`reportecalidad` (
  `idCalidad` INT NOT NULL AUTO_INCREMENT,
  `hecho_por` VARCHAR(255) NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `problema` VARCHAR(255) NULL DEFAULT NULL,
  `medio` VARCHAR(255) NULL DEFAULT NULL,
  `excelente` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idCalidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecfabricacion`.`reportefabricacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`reportefabricacion` (
  `idReporte` INT NOT NULL AUTO_INCREMENT,
  `nombreOperario` VARCHAR(255) NULL DEFAULT NULL,
  `cargo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `reporteDescripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idReporte`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecfabricacion`.`tareaasignar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`tareaasignar` (
  `idTarea` INT NOT NULL AUTO_INCREMENT,
  `asignada_por` VARCHAR(255) NULL DEFAULT NULL,
  `seleciona_area` VARCHAR(225) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_Inicial` DATE NULL DEFAULT NULL,
  `fecha_Final` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idTarea`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecfabricacion`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecfabricacion`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(50) NOT NULL,
  `nombreApellido` VARCHAR(100) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `roles` VARCHAR(50) NOT NULL,
  `departamento` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `tareaasignar_idTarea` INT NOT NULL,
  `reportecalidad_idCalidad` INT NOT NULL,
  `bodega_idBodega` INT NOT NULL,
  `reportefabricacion_idReporte` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `tareaasignar_idTarea`, `reportecalidad_idCalidad`, `bodega_idBodega`, `reportefabricacion_idReporte`),
  CONSTRAINT `fk_usuarios_tareaasignar`
    FOREIGN KEY (`tareaasignar_idTarea`)
    REFERENCES `proyecfabricacion`.`tareaasignar` (`idTarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_reportecalidad1`
    FOREIGN KEY (`reportecalidad_idCalidad`)
    REFERENCES `proyecfabricacion`.`reportecalidad` (`idCalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_bodega1`
    FOREIGN KEY (`bodega_idBodega`)
    REFERENCES `proyecfabricacion`.`bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_reportefabricacion1`
    FOREIGN KEY (`reportefabricacion_idReporte`)
    REFERENCES `proyecfabricacion`.`reportefabricacion` (`idReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `cedula` ON `proyecfabricacion`.`usuarios` (`cedula` ASC) VISIBLE;

CREATE UNIQUE INDEX `correo` ON `proyecfabricacion`.`usuarios` (`correo` ASC) VISIBLE;

CREATE INDEX `fk_usuarios_tareaasignar_idx` ON `proyecfabricacion`.`usuarios` (`tareaasignar_idTarea` ASC) VISIBLE;

CREATE INDEX `fk_usuarios_reportecalidad1_idx` ON `proyecfabricacion`.`usuarios` (`reportecalidad_idCalidad` ASC) VISIBLE;

CREATE INDEX `fk_usuarios_bodega1_idx` ON `proyecfabricacion`.`usuarios` (`bodega_idBodega` ASC) VISIBLE;

CREATE INDEX `fk_usuarios_reportefabricacion1_idx` ON `proyecfabricacion`.`usuarios` (`reportefabricacion_idReporte` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
